language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
  - 5.6
matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - composer update --no-interaction --prefer-dist
  - composer require codeclimate/php-test-reporter:dev-master --dev

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=31adf4688e9461406319fdcd9692bc6661c23ccb37a5e7b24be0bd83856fcaed ./vendor/bin/test-reporter